server:
  port: 8081

spring:
  datasource.url: jdbc:mysql://gateway_db:3306/gateway?useSSL=false
  datasource.username: root
  datasource.password: gateway
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update



logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type: TRACE
